name: Scala CI

on:
  push:
    branches: [ CI, DesignPattern2 ]
  pull_request:
    branches: [ CI, DesignPattern2 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v3
      - with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Set up sbt
        uses: sbt/setup-sbt@v1

      - name: Run tests with coverage
        run: sbt clean coverage test

      - name: Upload coverage to Coveralls
        run: sbr coverageReport coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}





